In [1]:
import numpy as np

In [2]:
#checking numpy version
print(np.__version__)

2.2.0


In [5]:
# creating array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [7]:
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.itemsize)

(5,)
int64
1
5
8


In [8]:
#updating array
a[1] = 10
print(a)

[ 1 10  3  4  5]


In [10]:
#Creating another array to multiple
b = a * np.array([6,7,8,9,10])
print(b)

[ 6 70 24 36 50]


In [16]:
# for dot product numpy is cool
#in basic python
l1 = [1,2,3]
l2 = [4,5,6]
dot = 0
for i in range (len(l1)):
    dot += l1[i] * l2[i]
print(dot)

32


In [17]:
# in numpy we can do this one line
numPD = np.dot(l1,l2)
print(numPD)

32


In [21]:
# There so many option lets look another
a1= np.array(l1)
a2= np.array(l2)
sum1 = a1 * a2
dot = np.sum(sum1)
print(dot)

32
